query getInventory($sku: ID!){
  product(identifier:{field: sku, value:$sku})@context(provider: "vtex.search-graphql"){
    items{
      ean,
      sellers{
        sellerName,
        commertialOffer{
          AvailableQuantity
        }
      }
    }
  }
}